baseURL = "https://dev.saito.page"
publishDir = "docs"
languageCode = 'ja-jp'
pagenate = 5
title = 'ksaito.dev'
theme = 'PaperMod'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
enableInlineShortcodes = true

[minify]
  disableXML = true
  minifyOutput = true

[params]
  title = 'ksaito.dev'
  description = ''
  author = 'ksaito'
  DateFormat = '2006-01-02'
  defaultTheme = 'auto'
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hidesummary = false
  showtoc = true
  tocopen = false
  ShareButtons = ['x', 'reddit']

# [[params.assets]]
#   favicon = ''
#   favicon16x16 = ''
#   favicon32x32 = ''
#   apple_touch_icon = ''
#   safari_pinned_tab = ''

# [[params.label]]
#   text = 'Home'
#   icon = ''
#   iconHeight = 35

[params.profileMode]
  enabled = false

[params.homeInfoParams]
  Title = 'ksaito blog'

[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/ksaito422'
[[params.socialIcons]]
  name = 'x'
  url = 'https://x.com/ksaito422'

# [editPost]
#   URL = 'https://github.com/ksaito422/blog'
#   Text = 'Suggest Changes'
#   appendFilePath = true

[[menu.main]]
  identifier = 'Archives'
  name = 'Archives'
  url = '/archives/'
  weight = 10

[[menu.main]]
  identifier = 'Tags'
  name = 'Tags'
  url = '/tags/'
  weight = 10

[[menu.main]]
  identifier = 'Search'
  name = 'Search'
  url = '/search/'
  weight = 10

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[markup.highlight]
  lineNos = true
